tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash"
brew "direnv"
brew "git"
brew "gnu-sed"
brew "mas"
brew "pre-commit"
brew "node"
cask "alfred"
cask "authy"
cask "discord"
cask "firefox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keybase"
cask "mullvadvpn"
cask "notion"
cask "omnifocus"
cask "postman"
cask "raindropio"
cask "signal"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "twitch"
cask "visual-studio-code"
cask "sqlectron"
cask "sublime-merge"
mas "1Password 7", id: 1333542190
mas "Airmail", id: 918858936
mas "Bear", id: 1091189122
mas "GIPHY CAPTURE", id: 668208984
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Trello", id: 1278508951

# Kubernetes essentials
brew "kubernetes-cli"
brew "kubernetes-helm"
cask "docker"
cask "google-cloud-sdk"
cask "virtualbox"
cask "minikube"
