tap "homebrew/cask"
brew "git"
brew "subliminal"
brew "tvnamer"
brew "docker"
brew "docker-compose"
brew "docker-machine"
cask "iterm2"
cask "keybase"
cask "google-chrome"
cask "firefox"
cask "authy"
cask "alfred"
cask "omnifocus"
cask "signal"
cask "telegram"
cask "transmission"
cask "slack"
cask "numi"
cask "vlc"
cask "jetbrains-toolbox"
cask "visual-studio-code"
cask "docker"
cask "robo-3t"
cask "gitkraken"
cask "spotify"
cask "karabiner-elements"
cask "notion"
cask "skype"
mas "1password", id: 1333542190
mas "airmail", id: 918858936
mas "trello", id: 1278508951
mas "bear", id: 1091189122
